// plaid_snapshot.proto — the bankferry→finance2 investments contract
// (docs/design/plaid-investments-pipeline.md).
//
// PRIMARY SOURCE: bankferry (ruling, Jeff 2026-07-17) — finance2
// carries this verbatim clone for its own codegen; contract changes
// land in bankferry first once its copy exists. Deliberately
// self-contained (no imports) so the file clones between repos with
// zero dependencies.
//
// Hard rules: no float/double anywhere near money or quantities —
// exact decimal strings end to end (bankferry fetches via raw-JSON
// json.Number; the official SDKs decode money as floats). No secrets:
// item_ref and account_ref are opaque identifiers, never access
// tokens. Snapshot files hold real account data — they are never repo
// content in either project.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/plaid_snapshot.proto

package investments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvestmentsSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bumped on any breaking change; a reader that does not know the
	// version rejects the snapshot loudly rather than misreading it.
	SchemaVersion int32           `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // currently 1
	AsOf          *Date           `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`                             // the fetch date (civil, no timezone)
	Items         []*ItemSnapshot `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentsSnapshot) Reset() {
	*x = InvestmentsSnapshot{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentsSnapshot) ProtoMessage() {}

func (x *InvestmentsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentsSnapshot.ProtoReflect.Descriptor instead.
func (*InvestmentsSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *InvestmentsSnapshot) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *InvestmentsSnapshot) GetAsOf() *Date {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *InvestmentsSnapshot) GetItems() []*ItemSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstitutionEntry string                 `protobuf:"bytes,1,opt,name=institution_entry,json=institutionEntry,proto3" json:"institution_entry,omitempty"` // Plaid institution name, e.g. "Vanguard"
	ItemRef          string                 `protobuf:"bytes,2,opt,name=item_ref,json=itemRef,proto3" json:"item_ref,omitempty"`                            // opaque, stable per item — never the access token
	Accounts         []*Account             `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ItemSnapshot) Reset() {
	*x = ItemSnapshot{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSnapshot) ProtoMessage() {}

func (x *ItemSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSnapshot.ProtoReflect.Descriptor instead.
func (*ItemSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ItemSnapshot) GetInstitutionEntry() string {
	if x != nil {
		return x.InstitutionEntry
	}
	return ""
}

func (x *ItemSnapshot) GetItemRef() string {
	if x != nil {
		return x.ItemRef
	}
	return ""
}

func (x *ItemSnapshot) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Account struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	AccountRef       string                   `protobuf:"bytes,1,opt,name=account_ref,json=accountRef,proto3" json:"account_ref,omitempty"` // Plaid account_id (opaque)
	Name             string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OfficialName     string                   `protobuf:"bytes,3,opt,name=official_name,json=officialName,proto3" json:"official_name,omitempty"`             // Plaid's longer name, when present
	Mask             string                   `protobuf:"bytes,4,opt,name=mask,proto3" json:"mask,omitempty"`                                                 // last digits — the human's matching aid
	Type             string                   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                                 // e.g. "investment"
	Subtype          string                   `protobuf:"bytes,6,opt,name=subtype,proto3" json:"subtype,omitempty"`                                           // e.g. "401k", "brokerage", "roth"
	InstitutionValue *Money                   `protobuf:"bytes,7,opt,name=institution_value,json=institutionValue,proto3" json:"institution_value,omitempty"` // institution-reported total value
	CashBalance      *Money                   `protobuf:"bytes,8,opt,name=cash_balance,json=cashBalance,proto3" json:"cash_balance,omitempty"`                // cash/sweep component, when reported
	Holdings         []*Holding               `protobuf:"bytes,9,rep,name=holdings,proto3" json:"holdings,omitempty"`
	Transactions     []*InvestmentTransaction `protobuf:"bytes,10,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetAccountRef() string {
	if x != nil {
		return x.AccountRef
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetOfficialName() string {
	if x != nil {
		return x.OfficialName
	}
	return ""
}

func (x *Account) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Account) GetInstitutionValue() *Money {
	if x != nil {
		return x.InstitutionValue
	}
	return nil
}

func (x *Account) GetCashBalance() *Money {
	if x != nil {
		return x.CashBalance
	}
	return nil
}

func (x *Account) GetHoldings() []*Holding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

func (x *Account) GetTransactions() []*InvestmentTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type Holding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Security         *SecurityRef           `protobuf:"bytes,1,opt,name=security,proto3" json:"security,omitempty"`
	Quantity         *Decimal               `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CostBasis        *Money                 `protobuf:"bytes,3,opt,name=cost_basis,json=costBasis,proto3" json:"cost_basis,omitempty"`                      // aggregate as reported; may be absent
	InstitutionPrice *Money                 `protobuf:"bytes,4,opt,name=institution_price,json=institutionPrice,proto3" json:"institution_price,omitempty"` // institution-reported price per unit
	PriceAsOf        *Date                  `protobuf:"bytes,5,opt,name=price_as_of,json=priceAsOf,proto3" json:"price_as_of,omitempty"`
	InstitutionValue *Money                 `protobuf:"bytes,6,opt,name=institution_value,json=institutionValue,proto3" json:"institution_value,omitempty"` // institution-reported position value
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *Holding) GetSecurity() *SecurityRef {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Holding) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Holding) GetCostBasis() *Money {
	if x != nil {
		return x.CostBasis
	}
	return nil
}

func (x *Holding) GetInstitutionPrice() *Money {
	if x != nil {
		return x.InstitutionPrice
	}
	return nil
}

func (x *Holding) GetPriceAsOf() *Date {
	if x != nil {
		return x.PriceAsOf
	}
	return nil
}

func (x *Holding) GetInstitutionValue() *Money {
	if x != nil {
		return x.InstitutionValue
	}
	return nil
}

type SecurityRef struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlaidSecurityId  string                 `protobuf:"bytes,1,opt,name=plaid_security_id,json=plaidSecurityId,proto3" json:"plaid_security_id,omitempty"`
	Ticker           string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"` // any of ticker/cusip/isin may be empty
	Cusip            string                 `protobuf:"bytes,3,opt,name=cusip,proto3" json:"cusip,omitempty"`
	Isin             string                 `protobuf:"bytes,4,opt,name=isin,proto3" json:"isin,omitempty"`
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type             string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // ISO 4217
	IsCashEquivalent bool                   `protobuf:"varint,8,opt,name=is_cash_equivalent,json=isCashEquivalent,proto3" json:"is_cash_equivalent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SecurityRef) Reset() {
	*x = SecurityRef{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRef) ProtoMessage() {}

func (x *SecurityRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRef.ProtoReflect.Descriptor instead.
func (*SecurityRef) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityRef) GetPlaidSecurityId() string {
	if x != nil {
		return x.PlaidSecurityId
	}
	return ""
}

func (x *SecurityRef) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *SecurityRef) GetCusip() string {
	if x != nil {
		return x.Cusip
	}
	return ""
}

func (x *SecurityRef) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *SecurityRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecurityRef) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *SecurityRef) GetIsCashEquivalent() bool {
	if x != nil {
		return x.IsCashEquivalent
	}
	return false
}

type InvestmentTransaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionRef string                 `protobuf:"bytes,1,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"` // Plaid investment_transaction_id (opaque)
	Date           *Date                  `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // buy | sell | cash | fee | transfer | ...
	Subtype        string                 `protobuf:"bytes,5,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Security       *SecurityRef           `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"` // absent for account-level cash/fee rows
	Quantity       *Decimal               `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount         *Money                 `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Price          *Money                 `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Fees           *Money                 `protobuf:"bytes,10,opt,name=fees,proto3" json:"fees,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvestmentTransaction) Reset() {
	*x = InvestmentTransaction{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentTransaction) ProtoMessage() {}

func (x *InvestmentTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentTransaction.ProtoReflect.Descriptor instead.
func (*InvestmentTransaction) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *InvestmentTransaction) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

func (x *InvestmentTransaction) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *InvestmentTransaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvestmentTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InvestmentTransaction) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *InvestmentTransaction) GetSecurity() *SecurityRef {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *InvestmentTransaction) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *InvestmentTransaction) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *InvestmentTransaction) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *InvestmentTransaction) GetFees() *Money {
	if x != nil {
		return x.Fees
	}
	return nil
}

// Exact decimal string, e.g. "1234.5600" — never float/double.
type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *Decimal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *Decimal               `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // ISO 4217
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *Money) GetAmount() *Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

// Civil calendar date; no time of day, no timezone.
type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"` // 1-12
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`     // 1-31
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_proto_plaid_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plaid_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_proto_plaid_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

var File_proto_plaid_snapshot_proto protoreflect.FileDescriptor

const file_proto_plaid_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/plaid_snapshot.proto\x12\x15bankferry.investments\"\xa9\x01\n" +
	"\x13InvestmentsSnapshot\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x120\n" +
	"\x05as_of\x18\x02 \x01(\v2\x1b.bankferry.investments.DateR\x04asOf\x129\n" +
	"\x05items\x18\x03 \x03(\v2#.bankferry.investments.ItemSnapshotR\x05items\"\x92\x01\n" +
	"\fItemSnapshot\x12+\n" +
	"\x11institution_entry\x18\x01 \x01(\tR\x10institutionEntry\x12\x19\n" +
	"\bitem_ref\x18\x02 \x01(\tR\aitemRef\x12:\n" +
	"\baccounts\x18\x03 \x03(\v2\x1e.bankferry.investments.AccountR\baccounts\"\xbf\x03\n" +
	"\aAccount\x12\x1f\n" +
	"\vaccount_ref\x18\x01 \x01(\tR\n" +
	"accountRef\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rofficial_name\x18\x03 \x01(\tR\fofficialName\x12\x12\n" +
	"\x04mask\x18\x04 \x01(\tR\x04mask\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x06 \x01(\tR\asubtype\x12I\n" +
	"\x11institution_value\x18\a \x01(\v2\x1c.bankferry.investments.MoneyR\x10institutionValue\x12?\n" +
	"\fcash_balance\x18\b \x01(\v2\x1c.bankferry.investments.MoneyR\vcashBalance\x12:\n" +
	"\bholdings\x18\t \x03(\v2\x1e.bankferry.investments.HoldingR\bholdings\x12P\n" +
	"\ftransactions\x18\n" +
	" \x03(\v2,.bankferry.investments.InvestmentTransactionR\ftransactions\"\x95\x03\n" +
	"\aHolding\x12>\n" +
	"\bsecurity\x18\x01 \x01(\v2\".bankferry.investments.SecurityRefR\bsecurity\x12:\n" +
	"\bquantity\x18\x02 \x01(\v2\x1e.bankferry.investments.DecimalR\bquantity\x12;\n" +
	"\n" +
	"cost_basis\x18\x03 \x01(\v2\x1c.bankferry.investments.MoneyR\tcostBasis\x12I\n" +
	"\x11institution_price\x18\x04 \x01(\v2\x1c.bankferry.investments.MoneyR\x10institutionPrice\x12;\n" +
	"\vprice_as_of\x18\x05 \x01(\v2\x1b.bankferry.investments.DateR\tpriceAsOf\x12I\n" +
	"\x11institution_value\x18\x06 \x01(\v2\x1c.bankferry.investments.MoneyR\x10institutionValue\"\xf6\x01\n" +
	"\vSecurityRef\x12*\n" +
	"\x11plaid_security_id\x18\x01 \x01(\tR\x0fplaidSecurityId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05cusip\x18\x03 \x01(\tR\x05cusip\x12\x12\n" +
	"\x04isin\x18\x04 \x01(\tR\x04isin\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12#\n" +
	"\rcurrency_code\x18\a \x01(\tR\fcurrencyCode\x12,\n" +
	"\x12is_cash_equivalent\x18\b \x01(\bR\x10isCashEquivalent\"\xcb\x03\n" +
	"\x15InvestmentTransaction\x12'\n" +
	"\x0ftransaction_ref\x18\x01 \x01(\tR\x0etransactionRef\x12/\n" +
	"\x04date\x18\x02 \x01(\v2\x1b.bankferry.investments.DateR\x04date\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\asubtype\x18\x05 \x01(\tR\asubtype\x12>\n" +
	"\bsecurity\x18\x06 \x01(\v2\".bankferry.investments.SecurityRefR\bsecurity\x12:\n" +
	"\bquantity\x18\a \x01(\v2\x1e.bankferry.investments.DecimalR\bquantity\x124\n" +
	"\x06amount\x18\b \x01(\v2\x1c.bankferry.investments.MoneyR\x06amount\x122\n" +
	"\x05price\x18\t \x01(\v2\x1c.bankferry.investments.MoneyR\x05price\x120\n" +
	"\x04fees\x18\n" +
	" \x01(\v2\x1c.bankferry.investments.MoneyR\x04fees\"\x1f\n" +
	"\aDecimal\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"d\n" +
	"\x05Money\x126\n" +
	"\x06amount\x18\x01 \x01(\v2\x1e.bankferry.investments.DecimalR\x06amount\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\tR\fcurrencyCode\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03dayBT\n" +
	"\x1bnet.stewart.bankferry.protoP\x01Z3github.com/jeffbstewart/bankferry/proto/investmentsb\x06proto3"

var (
	file_proto_plaid_snapshot_proto_rawDescOnce sync.Once
	file_proto_plaid_snapshot_proto_rawDescData []byte
)

func file_proto_plaid_snapshot_proto_rawDescGZIP() []byte {
	file_proto_plaid_snapshot_proto_rawDescOnce.Do(func() {
		file_proto_plaid_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plaid_snapshot_proto_rawDesc), len(file_proto_plaid_snapshot_proto_rawDesc)))
	})
	return file_proto_plaid_snapshot_proto_rawDescData
}

var file_proto_plaid_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_plaid_snapshot_proto_goTypes = []any{
	(*InvestmentsSnapshot)(nil),   // 0: bankferry.investments.InvestmentsSnapshot
	(*ItemSnapshot)(nil),          // 1: bankferry.investments.ItemSnapshot
	(*Account)(nil),               // 2: bankferry.investments.Account
	(*Holding)(nil),               // 3: bankferry.investments.Holding
	(*SecurityRef)(nil),           // 4: bankferry.investments.SecurityRef
	(*InvestmentTransaction)(nil), // 5: bankferry.investments.InvestmentTransaction
	(*Decimal)(nil),               // 6: bankferry.investments.Decimal
	(*Money)(nil),                 // 7: bankferry.investments.Money
	(*Date)(nil),                  // 8: bankferry.investments.Date
}
var file_proto_plaid_snapshot_proto_depIdxs = []int32{
	8,  // 0: bankferry.investments.InvestmentsSnapshot.as_of:type_name -> bankferry.investments.Date
	1,  // 1: bankferry.investments.InvestmentsSnapshot.items:type_name -> bankferry.investments.ItemSnapshot
	2,  // 2: bankferry.investments.ItemSnapshot.accounts:type_name -> bankferry.investments.Account
	7,  // 3: bankferry.investments.Account.institution_value:type_name -> bankferry.investments.Money
	7,  // 4: bankferry.investments.Account.cash_balance:type_name -> bankferry.investments.Money
	3,  // 5: bankferry.investments.Account.holdings:type_name -> bankferry.investments.Holding
	5,  // 6: bankferry.investments.Account.transactions:type_name -> bankferry.investments.InvestmentTransaction
	4,  // 7: bankferry.investments.Holding.security:type_name -> bankferry.investments.SecurityRef
	6,  // 8: bankferry.investments.Holding.quantity:type_name -> bankferry.investments.Decimal
	7,  // 9: bankferry.investments.Holding.cost_basis:type_name -> bankferry.investments.Money
	7,  // 10: bankferry.investments.Holding.institution_price:type_name -> bankferry.investments.Money
	8,  // 11: bankferry.investments.Holding.price_as_of:type_name -> bankferry.investments.Date
	7,  // 12: bankferry.investments.Holding.institution_value:type_name -> bankferry.investments.Money
	8,  // 13: bankferry.investments.InvestmentTransaction.date:type_name -> bankferry.investments.Date
	4,  // 14: bankferry.investments.InvestmentTransaction.security:type_name -> bankferry.investments.SecurityRef
	6,  // 15: bankferry.investments.InvestmentTransaction.quantity:type_name -> bankferry.investments.Decimal
	7,  // 16: bankferry.investments.InvestmentTransaction.amount:type_name -> bankferry.investments.Money
	7,  // 17: bankferry.investments.InvestmentTransaction.price:type_name -> bankferry.investments.Money
	7,  // 18: bankferry.investments.InvestmentTransaction.fees:type_name -> bankferry.investments.Money
	6,  // 19: bankferry.investments.Money.amount:type_name -> bankferry.investments.Decimal
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_plaid_snapshot_proto_init() }
func file_proto_plaid_snapshot_proto_init() {
	if File_proto_plaid_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plaid_snapshot_proto_rawDesc), len(file_proto_plaid_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_plaid_snapshot_proto_goTypes,
		DependencyIndexes: file_proto_plaid_snapshot_proto_depIdxs,
		MessageInfos:      file_proto_plaid_snapshot_proto_msgTypes,
	}.Build()
	File_proto_plaid_snapshot_proto = out.File
	file_proto_plaid_snapshot_proto_goTypes = nil
	file_proto_plaid_snapshot_proto_depIdxs = nil
}
